import asyncio
import sys
from mcp import ClientSession, StdioServerParameters
from mcp.client.stdio import stdio_client
from mcp.client.streamable_http import streamablehttp_client
from mcp.types import Root, CreateMessageResult, TextContent

# ---------- SAMPLING CALLBACK ----------
# Runs on CLIENT side whenever server calls create_message()
async def sampling_callback(context, params):
    print(f"[Sampling requested] Server sent: {params.messages}")
    fake_llm_response = "This is a summary generated by client's LLM."  # plug real Claude API call here
    return CreateMessageResult(
        role="assistant",
        content=TextContent(type="text", text=fake_llm_response),
        model="demo-model",
    )

# ---------- ELICITATION CALLBACK ----------
# Runs on CLIENT side whenever server calls ctx.elicit()
async def elicitation_callback(context, params):
    print(f"[Elicitation requested] {params.message}")
    user_input = input("Your answer: ")   # in a real app, show a UI form instead
    return {"action": "accept", "content": user_input}

# ---------- ROOTS CALLBACK ----------
# Runs on CLIENT side whenever server calls list_roots()
async def list_roots_callback(context):
    return [
        Root(uri="file:///home/user/project", name="My Project"),
        Root(uri="file:///home/user/documents", name="Documents"),
    ]

async def run_session(read, write):
    async with ClientSession(
        read, write,
        sampling_callback=sampling_callback,
        elicitation_callback=elicitation_callback,
        list_roots_callback=list_roots_callback,
    ) as session:
        await session.initialize()   # handshake - always first

        # TOOLS
        tools = await session.list_tools()
        print("Tools:", [t.name for t in tools.tools])
        print(await session.call_tool("add_numbers", {"a": 5, "b": 3}))

        # SAMPLING flow
        print(await session.call_tool("ask_ai_to_summarize", {"text": "Long text here..."}))

        # ELICITATION flow
        print(await session.call_tool("book_meeting", {"topic": "Sprint Planning"}))

        # ROOTS flow
        print(await session.call_tool("show_client_roots", {}))

        # RESOURCES
        print(await session.list_resources())
        print(await session.read_resource("config://server-info"))

        # PROMPTS
        print(await session.list_prompts())
        print(await session.get_prompt("code_review_prompt", {"code": "def f(): pass"}))

async def run_stdio():
    server_params = StdioServerParameters(command="python", args=["server.py"])
    async with stdio_client(server_params) as (read, write):
        await run_session(read, write)

async def run_http():
    async with streamablehttp_client("http://localhost:8000/mcp") as (read, write, _):
        await run_session(read, write)

if __name__ == "__main__":
    mode = sys.argv[1] if len(sys.argv) > 1 else "stdio"
    asyncio.run(run_http() if mode == "http" else run_stdio()) 